### ISSUE TITLE
Click on BTP Sync crashes container

### ISSUE THREAD

**Issue by hnlvc** [phihag/bts#41]
When enabling BTP sync, the umpires are pulled, and right after that the container crashes and is not able to start again. No match sync is possible.

**Comment by saschaheinl** [comment]
This comes up when International and Team competition is selected, here is an example on how it looks like inside the logs: 
```
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  | /bts/bts/btp_sync.js:182
bts-bts-1  |            const draw = draws.get(bm.DrawID[0]);
bts-bts-1  |                                            ^
bts-bts-1  | 
bts-bts-1  | TypeError: Cannot read properties of undefined (reading '0')
bts-bts-1  |     at /bts/bts/btp_sync.js:182:35
bts-bts-1  |     at /bts/node_modules/async/dist/async.js:2138:44
bts-bts-1  |     at eachOfArrayLike (/bts/node_modules/async/dist/async.js:502:13)
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)
bts-bts-1  | 
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  | /bts/bts/btp_sync.js:182
bts-bts-1  |            const draw = draws.get(bm.DrawID[0]);
bts-bts-1  |                                            ^
bts-bts-1  | 
bts-bts-1  | TypeError: Cannot read properties of undefined (reading '0')
bts-bts-1  |     at /bts/bts/btp_sync.js:182:35
bts-bts-1  |     at /bts/node_modules/async/dist/async.js:2138:44
bts-bts-1  |     at eachOfArrayLike (/bts/node_modules/async/dist/async.js:502:13)
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)
bts-bts-1  | 
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  | /bts/bts/btp_sync.js:182
bts-bts-1  |            const draw = draws.get(bm.DrawID[0]);
bts-bts-1  |                                            ^
bts-bts-1  | 
bts-bts-1  | TypeError: Cannot read properties of undefined (reading '0')
bts-bts-1  |     at /bts/bts/btp_sync.js:182:35
bts-bts-1  |     at /bts/node_modules/async/dist/async.js:2138:44
bts-bts-1  |     at eachOfArrayLike (/bts/node_modules/async/dist/async.js:502:13)
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)
bts-bts-1  | 
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  | /bts/bts/btp_sync.js:182
bts-bts-1  |            const draw = draws.get(bm.DrawID[0]);
bts-bts-1  |                                            ^
bts-bts-1  | 
bts-bts-1  | TypeError: Cannot read properties of undefined (reading '0')
bts-bts-1  |     at /bts/bts/btp_sync.js:182:35
bts-bts-1  |     at /bts/node_modules/async/dist/async.js:2138:44
bts-bts-1  |     at eachOfArrayLike (/bts/node_modules/async/dist/async.js:502:13)
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)
bts-bts-1  | 
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  | /bts/bts/btp_sync.js:182
bts-bts-1  |            const draw = draws.get(bm.DrawID[0]);
bts-bts-1  |                                            ^
bts-bts-1  | 
bts-bts-1  | TypeError: Cannot read properties of undefined (reading '0')
bts-bts-1  |     at /bts/bts/btp_sync.js:182:35
bts-bts-1  |     at /bts/node_modules/async/dist/async.js:2138:44
bts-bts-1  |     at eachOfArrayLike (/bts/node_modules/async/dist/async.js:502:13)
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)
bts-bts-1  | 
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)
bts-bts-1  | 
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  | /bts/bts/btp_sync.js:182
bts-bts-1  |            const draw = draws.get(bm.DrawID[0]);
bts-bts-1  |                                            ^
bts-bts-1  | 
bts-bts-1  | TypeError: Cannot read properties of undefined (reading '0')
bts-bts-1  |     at /bts/bts/btp_sync.js:182:35
bts-bts-1  |     at /bts/node_modules/async/dist/async.js:2138:44
bts-bts-1  |     at eachOfArrayLike (/bts/node_modules/async/dist/async.js:502:13)
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)
bts-bts-1  | 
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  | /bts/bts/btp_sync.js:182
bts-bts-1  |            const draw = draws.get(bm.DrawID[0]);
bts-bts-1  |                                            ^
bts-bts-1  | 
bts-bts-1  | TypeError: Cannot read properties of undefined (reading '0')
bts-bts-1  |     at /bts/bts/btp_sync.js:182:35
bts-bts-1  |     at /bts/node_modules/async/dist/async.js:2138:44
bts-bts-1  |     at eachOfArrayLike (/bts/node_modules/async/dist/async.js:502:13)
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)
bts-bts-1  | 
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  | /bts/bts/btp_sync.js:182
bts-bts-1  |            const draw = draws.get(bm.DrawID[0]);
bts-bts-1  |                                            ^
bts-bts-1  | 
bts-bts-1  | TypeError: Cannot read properties of undefined (reading '0')
bts-bts-1  |     at /bts/bts/btp_sync.js:182:35
bts-bts-1  |     at /bts/node_modules/async/dist/async.js:2138:44
bts-bts-1  |     at eachOfArrayLike (/bts/node_modules/async/dist/async.js:502:13)
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)
bts-bts-1  | 
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  | /bts/bts/btp_sync.js:182
bts-bts-1  |            const draw = draws.get(bm.DrawID[0]);
bts-bts-1  |                                            ^
bts-bts-1  | 
bts-bts-1  | TypeError: Cannot read properties of undefined (reading '0')
bts-bts-1  |     at /bts/bts/btp_sync.js:182:35
bts-bts-1  |     at /bts/node_modules/async/dist/async.js:2138:44
bts-bts-1  |     at eachOfArrayLike (/bts/node_modules/async/dist/async.js:502:13)
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)
bts-bts-1  | 
bts-bts-1  | Node.js v20.8.0
bts-bts-1  | make: *** [Makefile:31: run] Error 1
bts-bts-1  | /bts/bts/btp_sync.js:182
bts-bts-1  |            const draw = draws.get(bm.DrawID[0]);
bts-bts-1  |                                            ^
bts-bts-1  | 
bts-bts-1  | TypeError: Cannot read properties of undefined (reading '0')
bts-bts-1  |     at /bts/bts/btp_sync.js:182:35
bts-bts-1  |     at /bts/node_modules/async/dist/async.js:2138:44
bts-bts-1  |     at eachOfArrayLike (/bts/node_modules/async/dist/async.js:502:13)
bts-bts-1  |     at eachOf (/bts/node_modules/async/dist/async.js:553:16)
bts-bts-1  |     at awaitable(eachOf) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at Object.eachLimit (/bts/node_modules/async/dist/async.js:2200:16)
bts-bts-1  |     at awaitable(eachLimit) (/bts/node_modules/async/dist/async.js:206:32)
bts-bts-1  |     at integrate_matches (/bts/bts/btp_sync.js:181:8)
bts-bts-1  |     at /bts/bts/btp_sync.js:411:22
bts-bts-1  |     at nextTask (/bts/node_modules/async/dist/async.js:4554:13)

```
